channels:
  - conda-forge
name: coffee-bot
dependencies:
  - python=3.7
  - pip
  - python-dotenv
  - ruamel_yaml
  - incremental
  - fuzzywuzzy
  - numpy
  - pip:
    - rasa_core_sdk
    - chatette==1.4.2