name: coffee-bot-action
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - python-dotenv
  - numpy
  - ruamel_yaml
  - incremental
  - fuzzywuzzy
  - gunicorn=19.9
  - falcon=1.4.*
  - pip:
    - rasa-sdk
    - falcon-cors~=1.1
