version: '3.0'

services:
  rasa:
    image: rasa/rasa:latest-full
    networks: ['coffee-bot-network']
    ports:
    - "5005:5005"
    volumes:
    - "./bot-core/models:/app/models"
    - "./bot-core/config:/app/config"
    - "./logs:/app/logs"
    - "./bot-core/data:/app/data"
    restart: on-failure
    command: [ "run", "--debug", "-p", "5005", "--credentials", "./config/credentials.yml", "--endpoints", "./config/endpoints.yml"]

  action_server:
    build: ./action-server
    image: coffee-bof-action-server
    container_name: coffee-bof-action-server
    networks: ['coffee-bot-network']
    tty: true
    ports:
    - "5055:5055"
    environment:
        - SERVER_PORT=5055
        - NUMBER_OF_WORKERS=1
        - GUNICORN_TIMEOUT=300
        - LOGGING_CONFIG=/app/src/main/resources/config/logging_config.local.ini
    command: run
    volumes:
    - "./bot-core/src/main/python/actions:/app/actions"


  duckling:
    image: rasa/duckling
    networks: ['coffee-bot-network']
    ports:
    - "8000:8000"
  
  mongodb:
    image: mongo:4.0.2
    command: "mongod  --auth"
    ports:
      - "27017:27017"
    environment:
      - MONGOID_ENV=test
    volumes:
      - ./mongo:/data/db

  chatclient:
    build:
      context: ${CLIENT_HOME}
      dockerfile: Dockerfile
      args:
      - REACT_APP_DIALOGUE_RUN_PORT_SUFFIX=:9090
      - REACT_APP_DIALOGUE_UI_PORT_SUFFIX=:9090
      - REACT_APP_NLU_RUN_PORT_SUFFIX=:5000
      - REACT_APP_NLU_UI_PORT_SUFFIX=:5000
      - REACT_APP_DIALOGUE_LOGS_PORT_SUFFIX=:5050
      - REACT_APP_LOCALHOST_ONLY=true
    image: react-chatclient
    container_name: react-chatclient
    networks: ['coffee-bot-network']
    tty: true
    ports:
      - "8080:80"


networks: {coffee-bot-network: {}}
